// frontend1/src/components/adsy-news/header.tsx
import React, { useState, useEffect, useRef } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  Search,
  X,
  Calendar,
  Globe,
  BarChart2,
  ChevronDown,
  ChevronRight,
} from "lucide-react";

const Header: React.FC = () => {
  const router = useRouter();

  // State management
  const [logo, setLogo] = useState<string | null>(null);
  const [categories, setCategories] = useState<any[]>([]);
  const [activeCategory, setActiveCategory] = useState<string>("all");
  const [moreMenuOpen, setMoreMenuOpen] = useState(false);
  const [isSearchVisible, setIsSearchVisible] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [breakingNews, setBreakingNews] = useState<string[]>([]);

  const searchInputRef = useRef<HTMLInputElement>(null);

  // Fetch logo
  useEffect(() => {
    const fetchLogo = async () => {
      const response = await fetch("/api/news-logo");
      const data = await response.json();
      setLogo(data?.image || null);
    };
    fetchLogo();
  }, []);

  // Fetch categories
  useEffect(() => {
    const fetchCategories = async () => {
      const response = await fetch("/api/news/categories");
      const data = await response.json();
      setCategories(data?.results || []);
    };
    fetchCategories();
  }, []);

  // Fetch breaking news
  useEffect(() => {
    const fetchBreakingNews = async () => {
      const response = await fetch("/api/news/breaking-news");
      const data = await response.json();
      setBreakingNews(data?.map((news: any) => news.title) || []);
    };
    fetchBreakingNews();
  }, []);

  // Handle search input
  const handleSearchInput = async () => {
    if (!searchQuery.trim()) {
      setSearchResults([]);
      return;
    }
    setIsSearching(true);
    try {
      const response = await fetch(
        `/api/news/posts?search=${encodeURIComponent(searchQuery.trim())}`
      );
      const data = await response.json();
      setSearchResults(data?.results || []);
    } catch (error) {
      console.error("Error fetching search results:", error);
      setSearchResults([]);
    } finally {
      setIsSearching(false);
    }
  };

  // Clear search
  const clearSearch = () => {
    setSearchQuery("");
    setSearchResults([]);
  };

  // Navigate to article
  const navigateToArticle = (article: any) => {
    clearSearch();
    setIsSearchVisible(false);
    router.push(`/adsy-news/${article.slug}`);
  };

  // Format date
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  };

  return (
    <div>
      <header className="sticky top-0 z-50 bg-white shadow-md">
        <div className="max-w-7xl mx-auto">
          {/* Main Navigation */}
          <div className="flex items-center justify-between px-4 py-3 sm:py-4 lg:py-5 sm:px-6 lg:px-8">
            {/* Logo */}
            <Link href="/adsy-news">
              <a className="flex-shrink-0 mr-3">
                {logo && (
                  <img
                    src={logo}
                    alt="Adsy News Logo"
                    width="120"
                    height="40"
                    className="h-6 sm:h-8 w-auto object-contain"
                  />
                )}
              </a>
            </Link>

            {/* Desktop Nav Categories */}
            <nav className="hidden md:flex flex-1 justify-center space-x-4 lg:space-x-8">
              {categories.slice(0, 4).map((category) => (
                <Link key={category.id} href={`/adsy-news/categories/${category.slug}`}>
                  <a
                    className={`text-sm font-medium hover:text-primary transition-colors duration-200 py-1 ${
                      activeCategory === category.id
                        ? "text-primary border-b-2 border-primary"
                        : "text-gray-800"
                    }`}
                  >
                    {category.name}
                  </a>
                </Link>
              ))}
              {categories.length > 4 && (
                <div className="relative">
                  <button
                    onClick={() => setMoreMenuOpen(!moreMenuOpen)}
                    className="flex items-center text-sm font-medium text-gray-800 hover:text-primary transition-colors duration-200 py-1"
                  >
                    More
                    <ChevronDown className="ml-1" />
                  </button>
                  {moreMenuOpen && (
                    <div className="absolute top-full right-0 mt-1 bg-white shadow-lg rounded-md py-2 z-50 w-48 overflow-y-auto border border-gray-200">
                      {categories.slice(4).map((category) => (
                        <Link
                          key={category.id}
                          href={`/adsy-news/categories/${category.slug}`}
                        >
                          <a
                            className={`block px-4 py-2 text-sm hover:bg-gray-100 transition-colors ${
                              activeCategory === category.id
                                ? "text-primary"
                                : "text-gray-800"
                            }`}
                          >
                            {category.name}
                          </a>
                        </Link>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </nav>

            {/* Right Side Actions */}
            <div className="flex items-center space-x-1.5 sm:space-x-3">
              {/* Search Icon */}
              <button
                onClick={() => setIsSearchVisible(!isSearchVisible)}
                className="flex items-center justify-center h-9 w-9 rounded-full hover:bg-gray-100 text-gray-600 transition-colors"
                aria-label="Search"
              >
                <Search className="h-5 w-5" />
              </button>

              {/* Navigation Buttons */}
              <Link href="/">
                <a className="flex items-center gap-1.5 px-2.5 py-1.5 sm:px-3 sm:py-2 rounded-full text-xs sm:text-sm font-medium text-white bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-700 hover:to-indigo-800 transition-all">
                  <BarChart2 className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
                  <span>AdsyClub</span>
                </a>
              </Link>
              <Link href="/business-network">
                <a className="flex items-center gap-1.5 px-2.5 py-1.5 sm:px-3 sm:py-2 rounded-full text-xs sm:text-sm font-medium text-white bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 transition-all">
                  <Globe className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
                  <span>Adsy BN</span>
                </a>
              </Link>
            </div>
          </div>

          {/* Breaking News Ticker */}
          <div className="bg-primary text-white py-2.5 px-4 sm:px-6 rounded-lg shadow-md mt-3 mb-6 sm:mb-8">
            <div className="flex items-center">
              <div className="flex-shrink-0">
                <span className="font-semibold text-xs sm:text-base mr-3 sm:mr-4 border-r border-white/30 pr-3 sm:pr-4">
                  BREAKING
                </span>
              </div>
              <div className="overflow-hidden relative w-full">
                <div className="flex whitespace-nowrap animate-ticker">
                  {breakingNews.map((news, index) => (
                    <p
                      key={index}
                      className="ticker-item px-4 capitalize text-sm sm:text-base"
                    >
                      {news}
                    </p>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Search Overlay */}
      {isSearchVisible && (
        <div
          className="fixed inset-0 bg-black/20 backdrop-blur-sm z-50 flex items-start justify-center pt-20 px-4 sm:px-0"
          onClick={() => setIsSearchVisible(false)}
        >
          <div
            className="bg-white rounded-lg shadow-xl w-full max-w-lg transform transition-all duration-300 overflow-hidden"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="p-4 border-b border-gray-100">
              <div className="relative">
                <Search className="h-5 w-5 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <input
                  type="text"
                  placeholder="Search news articles..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  onInput={handleSearchInput}
                  className="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-full text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent bg-gray-50 text-gray-800"
                  ref={searchInputRef}
                />
                {searchQuery && (
                  <button
                    onClick={clearSearch}
                    className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                  >
                    <X className="h-4 w-4" />
                  </button>
                )}
              </div>
            </div>

            <div className="divide-y divide-gray-100 max-h-[60vh] overflow-y-auto">
              {searchQuery && searchResults.length > 0 ? (
                searchResults.map((result) => (
                  <div
                    key={result.id}
                    className="p-4 hover:bg-gray-50 cursor-pointer transition-colors"
                    onClick={() => navigateToArticle(result)}
                  >
                    <p className="font-medium text-gray-800 line-clamp-2 mb-1">
                      {result.title}
                    </p>
                    <div className="flex items-center text-xs text-gray-500">
                      <Calendar className="h-3 w-3 mr-1" />
                      {formatDate(result.created_at)}
                      <span className="mx-2">•</span>
                      <span className="bg-primary/10 text-primary px-2 py-0.5 rounded-full text-xs capitalize">
                        {result.categories?.[0]?.title || "News"}
                      </span>
                    </div>
                  </div>
                ))
              ) : isSearching ? (
                <div className="p-6 text-center">
                  <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-primary mx-auto"></div>
                  <p className="mt-4 text-gray-500">Searching...</p>
                </div>
              ) : (
                <div className="p-6 text-center text-gray-500">
                  <Search className="mx-auto h-8 w-8 text-gray-300 mb-2" />
                  <p>Type to start searching</p>
                  <p className="text-xs mt-1">Press ESC to close</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Header;

// frontend/components/adsy-news/header.vue
<template>
  <div>
    <header class="sticky top-0 z-50 bg-white shadow-md">
      <div class="max-w-7xl mx-auto">
        <!-- Main Navigation - REVISED LAYOUT -->
        <div class="flex items-center justify-between px-4 py-3 sm:py-4 lg:py-5 sm:px-6 lg:px-8">
          <!-- Logo - Now in the same row with increased size -->
          <NuxtLink to="/adsy-news" class="flex-shrink-0 mr-3">
            <NuxtImg
              v-if="logo[0]?.image"
              :src="logo[0].image"
              alt="Adsy News Logo"
              width="120"
              height="40"
              class="h-7 sm:h-9 w-auto object-contain" 
            />
          </NuxtLink>

          <!-- Desktop Nav Categories - Middle section -->
          <nav
            class="hidden md:flex flex-1 justify-center space-x-4 lg:space-x-8"
            v-if="categories?.length > 0"
          >
            <NuxtLink
              v-for="category in categories.slice(0, 6)"
              :key="category.id"
              :class="[
                'text-sm font-medium hover:text-primary transition-colors duration-200 py-1',
                activeCategory === category.id
                  ? 'text-primary border-b-2 border-primary'
                  : 'text-gray-800',
              ]"
              :to="`/adsy-news/categories/${category.slug}/`"
            >
              {{ category.name }}
            </NuxtLink>
            <div class="relative mt-1" v-if="categories.length > 4">
              <button
                @click="toggleMoreCategories"
                class="flex  items-center text-sm font-medium text-gray-800 hover:text-primary transition-colors duration-200"
              >
                More
                <UIcon name="i-heroicons-arrow-small-down-20-solid" class="ml-1" />
              </button>
              <!-- More menu dropdown - unchanged -->
              <div
                v-if="moreMenuOpen"
                class="absolute top-full right-0 mt-1 bg-white shadow-lg rounded-md py-2 z-50 w-48 overflow-y-auto border border-gray-200 transform origin-top-right"
                v-click-outside="() => (moreMenuOpen = false)"
              >
                <NuxtLink
                  v-for="category in categories.slice(4)"
                  :key="category.id"
                  :class="[
                    'block px-4 py-2 text-sm hover:bg-gray-100 transition-colors',
                    activeCategory === category.id
                      ? 'text-primary'
                      : 'text-gray-800',
                  ]"
                  :to="`/adsy-news/categories/${category.slug}/`"
                >
                  {{ category.name }}
                </NuxtLink>
              </div>
            </div>
          </nav>

          <!-- Right side actions - search and buttons -->
          <div class="flex items-center space-x-1.5 sm:space-x-3">
            <!-- Search icon -->
            <button
              @click="toggleSearch"
              class="flex items-center justify-center h-9 w-9 rounded-full hover:bg-gray-100 text-gray-600 transition-colors"
              aria-label="Search"
            >
              <SearchIcon class="h-5 w-5" />
            </button>
            
            <!-- Navigation Buttons -->
            <NuxtLink
              to="/"
              class="flex items-center gap-1.5 px-2.5 py-1.5 sm:px-3 sm:py-2 rounded-full text-xs sm:text-sm font-medium text-white bg-gradient-to-r from-blue-600 to-indigo-700 hover:from-blue-700 hover:to-indigo-800 transition-all"
              aria-label="Go to AdsyClub"
            >
              <BarChartBig class="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              <span>AdsyClub</span>
            </NuxtLink>
            
            <NuxtLink
              to="/business-network"
              class="flex items-center gap-1.5 px-2.5 py-1.5 sm:px-3 sm:py-2 rounded-full text-xs sm:text-sm font-medium text-white bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 transition-all"
              aria-label="Go to Business Network"
            >
              <Globe class="h-3.5 w-3.5 sm:h-4 sm:w-4" />
              <span>Adsy BN</span>
            </NuxtLink>
          </div>
        </div>
        
        <!-- Mobile Category Nav - CENTERED WITH FIXED DROPDOWN -->
        <div class="px-4 sm:px-6 lg:px-8 ">
          <nav
            class="flex md:hidden pb-3 mt-1 justify-center"
            v-if="categories?.length > 0"
          >
            <div class="flex space-x-4 overflow-x-auto scrollbar-hide">
              <NuxtLink
                v-for="category in categories.slice(0, 4)"
                :key="category.id"
                :class="[
                  'text-sm font-medium hover:text-primary transition-colors duration-200 py-1 flex-shrink-0',
                  activeCategory === category.id
                    ? 'text-primary border-b-2 border-primary'
                    : 'text-gray-800',
                ]"
                :to="`/adsy-news/categories/${category.slug}/`"
              >
                {{ category.name }}
              </NuxtLink>
              <div class="relative flex-shrink-0 pt-1" v-if="categories.length > 4">
                <button
                  @click="toggleMoreCategories"
                  class="flex items-center text-sm font-medium text-gray-800 hover:text-primary transition-colors duration-200"
                  aria-label="More categories"
                >
                  More
                  <UIcon name="i-heroicons-arrow-small-down-20-solid" class="ml-1" />
                </button>
                <!-- Mobile dropdown menu with fixed positioning -->
                <div
                  v-if="moreMenuOpen"
                  class="absolute top-full left-0 mt-1 bg-white shadow-lg rounded-md py-2 z-50 w-48 max-h-60 overflow-y-auto border border-gray-200"
                  v-click-outside="() => (moreMenuOpen = false)"
                  style="min-width: 150px;"
                >
                  <NuxtLink
                    v-for="category in categories.slice(4)"
                    :key="category.id"
                    :class="[
                      'block px-4 py-2 text-sm hover:bg-gray-100 transition-colors',
                      activeCategory === category.id
                        ? 'text-primary'
                        : 'text-gray-800',
                    ]"
                    :to="`/adsy-news/categories/${category.slug}/`"
                    @click="moreMenuOpen = false"
                  >
                    {{ category.name }}
                  </NuxtLink>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
    </header>

    <!-- Search Overlay -->
    <div
      v-if="isSearchVisible"
      class="fixed inset-0 bg-black/20 backdrop-blur-sm z-50 flex items-start justify-center pt-20 px-4 sm:px-0"
      @click="isSearchVisible = false"
    >
      <div 
        class="bg-white rounded-lg shadow-xl w-full max-w-lg transform transition-all duration-300 overflow-hidden"
        @click.stop
      >
        <div class="p-4 border-b border-gray-100">
          <div class="relative">
            <SearchIcon class="h-5 w-5 absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
            <input
              type="text"
              placeholder="Search news articles..."
              v-model="searchQuery"
              class="w-full pl-10 pr-4 py-2.5 border border-gray-300 rounded-full text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent bg-gray-50 text-gray-800"
              @input="handleSearchInput"
              ref="searchInputRef"
            />
            <button 
              v-if="searchQuery" 
              @click="clearSearch"
              class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
            >
              <XIcon class="h-4 w-4" />
            </button>
          </div>
        </div>

        <div v-if="searchQuery" class="divide-y divide-gray-100 max-h-[60vh] overflow-y-auto">
          <div
            v-for="result in searchResults"
            :key="result.id"
            class="p-4 hover:bg-gray-50 cursor-pointer transition-colors"
            @click="navigateToArticle(result)"
          >
            <p class="font-medium text-gray-800 line-clamp-2 mb-1">{{ result.title }}</p>
            <div class="flex items-center text-xs text-gray-500">
              <CalendarIcon class="h-3 w-3 mr-1" />
              {{ formatDate(result.created_at) }}
              <span class="mx-2">•</span>
              <span class="bg-primary/10 text-primary px-2 py-0.5 rounded-full text-xs capitalize">
                {{ result.categories && result.categories.length > 0 ? result.categories[0].title : "News" }}
              </span>
            </div>
          </div>
          
          <div
            v-if="searchResults.length === 0 && !isSearching && searchQuery"
            class="p-6 text-center text-gray-500"
          >
            <svg class="mx-auto h-12 w-12 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
            <p class="mt-4">No results found for "{{ searchQuery }}"</p>
            <p class="text-sm mt-2">Try using different keywords or check spelling</p>
          </div>
          
          <div v-if="isSearching" class="p-6 text-center">
            <div class="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-primary mx-auto"></div>
            <p class="mt-4 text-gray-500">Searching...</p>
          </div>
        </div>
        
        <div v-if="!searchQuery" class="p-6 text-center text-gray-500">
          <SearchIcon class="mx-auto h-8 w-8 text-gray-300 mb-2" />
          <p>Type to start searching</p>
          <p class="text-xs mt-1">Press ESC to close</p>
        </div>
      </div>
    </div>

    <!-- Breaking News Ticker -->
    <UContainer>
      <div class="bg-primary text-white py-2.5 px-4 sm:px-6 rounded-lg shadow-md mt-3 mb-6 sm:mb-8">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <span class="font-semibold text-xs sm:text-base mr-3 sm:mr-4 border-r border-white/30 pr-3 sm:pr-4">BREAKING</span>
          </div>
          <div class="overflow-hidden relative w-full">
            <transition-group
              name="ticker"
              tag="div"
              class="flex whitespace-nowrap ticker-container"
            >
              <p
                v-for="(news, index) in breakingNews"
                :key="index"
                class="ticker-item px-4 capitalize text-sm sm:text-base"
              >
                {{ news.title }}
              </p>
            </transition-group>
          </div>
        </div>
      </div>
    </UContainer>
  </div>
</template>

<script setup>
const { get } = useApi();
const logo = ref({});

async function getLogo() {
  const { data } = await get("/news-logo/");
  logo.value = data;
}
await getLogo();

import {
  SunIcon,
  XIcon,
  SearchIcon,
  CalendarIcon,
  CloudIcon,
  CloudRainIcon,
  Globe,        // Added for Business Network
  BarChartBig   // Added for AdsyClub
} from "lucide-vue-next";

import { onMounted, onUnmounted, nextTick } from "vue";

// Debounce utility function
function debounce(func, wait) {
  let timeout;
  return function (...args) {
    const context = this;
    clearTimeout(timeout);
    timeout = setTimeout(() => func.apply(context, args), wait);
  };
}

// Navigation state
const moreMenuOpen = ref(false);
const toggleMoreCategories = () => {
  moreMenuOpen.value = !moreMenuOpen.value;
};
const setMoreCategory = (categoryId) => {
  setActiveCategory(categoryId);
  moreMenuOpen.value = false;
};

// Search state
const searchQuery = ref("");
const searchResults = ref([]);
const isSearching = ref(false);
const isSearchVisible = ref(false);

// Add search input ref for focusing
const searchInputRef = ref(null);

// Update toggle search to focus input
const toggleSearch = () => {
  isSearchVisible.value = !isSearchVisible.value;

  // Focus the search input when the search bar is made visible
  if (isSearchVisible.value) {
    nextTick(() => {
      searchInputRef.value?.focus();
    });
  }
};

// Close search dropdown when clicking outside
const handleClickOutside = (event) => {
  const searchDropdown = document.querySelector(".search-dropdown");
  const searchIcon = document.querySelector(".search-icon");
  if (
    searchDropdown &&
    !searchDropdown.contains(event.target) &&
    searchIcon &&
    !searchIcon.contains(event.target)
  ) {
    isSearchVisible.value = false;
  }
};

// Add keyboard event listener for ESC key
onMounted(() => {
  // Don't remove your existing event listener
  document.addEventListener("click", handleClickOutside);
  
  // Add keyboard listener
  document.addEventListener("keydown", (e) => {
    if (e.key === 'Escape' && isSearchVisible.value) {
      isSearchVisible.value = false;
    }
  });
});

onUnmounted(() => {
  document.removeEventListener("click", handleClickOutside);
  document.removeEventListener("keydown", handleEscKey);
});

// Perform search when query changes
const performSearch = async () => {
  if (!searchQuery.value.trim()) {
    searchResults.value = [];
    return;
  }

  try {
    isSearching.value = true;
    // Make API call to fetch search results
    const { data } = await get(
      `/news/posts/?search=${encodeURIComponent(searchQuery.value.trim())}`
    );

    if (data && data.results) {
      searchResults.value = data.results;
    } else {
      searchResults.value = [];
    }
  } catch (error) {
    console.error("Error searching news:", error);
    searchResults.value = [];
  } finally {
    isSearching.value = false;
  }
};

// Debounce the search function to avoid too many API calls
const debouncedSearch = debounce(performSearch, 300);

// Clear search
const clearSearch = () => {
  searchQuery.value = "";
  searchResults.value = [];
};

// Function to handle input events
const handleSearchInput = () => {
  if (!searchQuery.value.trim()) {
    searchResults.value = [];
    return;
  }
  debouncedSearch();
};

// Navigate to article detail page when clicking on search result
const router = useRouter();
const navigateToArticle = (article) => {
  // Clear the search
  searchQuery.value = "";
  searchResults.value = [];
  isSearchVisible.value = false;

  // Navigate to the article detail page
  router.push(`/adsy-news/${article.slug}/`);
};

// Helper functions
const formatDate = (dateString) => {
  if (!dateString) return "";
  return new Date(dateString).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
};

// Categories
const categories = ref([]);

async function getCategories() {
  try {
    const res = await get("/news/categories/");
    if (res.data && res.data.results) {
      categories.value = res.data.results.map((category) => ({
        id: category.id,
        name: category.title,
        slug: category.slug,
      }));
    } else {
      console.error("Unexpected response format:", res.data);
    }
  } catch (error) {
    console.error("Error fetching categories:", error);
  }
}
await getCategories();

const activeCategory = ref("all");
const setActiveCategory = (categoryId) => {
  activeCategory.value = categoryId;
};

// Breaking news ticker
const breakingNews = ref([
  "Global Summit on Climate Change Reaches Historic Agreement",
  "New Technology Breakthrough Could Revolutionize Renewable Energy",
  "Major Economic Reform Bill Passes in Senate",
  "Scientists Discover Potential Cure for Rare Disease",
]);

async function getBreakingNews() {
  try {
    const res = await get("/news/breaking-news/");
    if (res.data) {
      breakingNews.value = res.data.map((news) => ({
        title: news.title,
        description: news.description,
      }));
    } else {
      console.error("Unexpected response format:", res.data);
    }
  } catch (error) {
    console.error("Error fetching breaking news:", error);
  }
}
await getBreakingNews();

// Current date
const currentDate = computed(() => {
  return new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
});

// Weather data (simulated)
const weather = reactive({
  temp: 24,
  condition: "Partly Cloudy",
  icon: "cloud",
});

// Tags for mobile menu
const tags = ref([]);

async function getTags() {
  try {
    const res = await get("/news/categories/");
    if (res.data && res.data.results) {
      tags.value = res.data.results;
    }
  } catch (error) {
    console.error("Error fetching tags:", error);
  }
}

await getTags();

// Chat opening logic
const openChat = () => {
  alert("Chat option opened!"); // Replace with actual chat opening logic
};

// Add this to implement click outside behavior
const vClickOutside = {
  mounted(el, binding) {
    el.clickOutsideEvent = (event) => {
      if (!(el === event.target || el.contains(event.target))) {
        binding.value(event);
      }
    };
    document.addEventListener('click', el.clickOutsideEvent);
  },
  unmounted(el) {
    document.removeEventListener('click', el.clickOutsideEvent);
  },
};
</script>

<style>
:root {
  --color-primary: #e53e3e;
  --color-primary-dark: #c53030;
}

.bg-primary {
  background-color: var(--color-primary);
}

.text-primary {
  color: var(--color-primary);
}

.hover\:text-primary:hover {
  color: var(--color-primary);
}

.hover\:text-primary-dark:hover {
  color: var(--color-primary-dark);
}

.hover\:bg-primary-dark:hover {
  background-color: var(--color-primary-dark);
}

.focus\:ring-primary:focus {
  --tw-ring-color: var(--color-primary);
}

.focus\:border-primary:focus {
  border-color: var(--color-primary);
}

.border-primary {
  border-color: var(--color-primary);
}

/* Hide scrollbar but maintain functionality */
.scrollbar-hide {
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* IE and Edge */
}

.scrollbar-hide::-webkit-scrollbar {
  display: none; /* Chrome, Safari and Opera */
}

/* Ticker animation */
.ticker-container {
  animation: ticker 20s linear infinite;
}

.ticker-item {
  margin-right: 50px;
}

@keyframes ticker {
  0% {
    transform: translateX(100%);
  }
  100% {
    transform: translateX(-100%);
  }
}

/* Transition effects */
.comment-list-enter-active,
.comment-list-leave-active {
  transition: all 0.5s ease;
}

.comment-list-enter-from,
.comment-list-leave-to {
  opacity: 0;
  transform: translateY(30px);
}

/* Line clamp for article summaries */
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
