// frontend1/src/components/qrcode/Stream.tsx
import React, { useEffect, useRef, useState } from 'react';
import QrScanner from 'qr-scanner';

interface StreamProps {
  onScanned: (result: string) => void;
}

const Stream: React.FC<StreamProps> = ({ onScanned }) => {
  const [qrCode, setQrCode] = useState<string | null>(null);
  const videoElement = useRef<HTMLVideoElement | null>(null);
  let qrScanner: QrScanner | null = null;

  useEffect(() => {
    if (videoElement.current) {
      qrScanner = new QrScanner(videoElement.current, (result) => {
        setQrCode(result);
        onScanned(result);
      });
      qrScanner.start();
    }

    return () => {
      if (qrScanner) {
        qrScanner.stop();
      }
    };
  }, [onScanned]);

  return (
    <div>
      <video
        className="max-sm:w-72 max-sm:h-72 mx-auto"
        ref={videoElement}
        width="100%"
        height="100%"
      ></video>
      {qrCode && (
        <div className="qr-result">
          <p>Scanned QR Code: {qrCode}</p>
        </div>
      )}
    </div>
  );
};

export default Stream;

// frontend/components/qrcode/stream.vue
<template>
  <div>
    <video
      class="max-h-[200px] max-w-[200px] mx-auto"
      ref="videoElement"
      width="100%"
      height="100%"
    ></video>
    <div v-if="qrCode" class="qr-result">
      <p>Scanned QR Code: {{ qrCode }}</p>
    </div>
  </div>
</template>

<script setup>
const emit = defineEmits(["scanned"]);
import QrScanner from "qr-scanner";

const qrCode = ref(null);
const videoElement = ref(null);
let qrScanner;

onMounted(() => {
  if (videoElement.value) {
    qrScanner = new QrScanner(videoElement.value, (result) => {
      qrCode.value = result; // Store the scanned QR code
      emit("scanned", result);
    });
    qrScanner.start();
  }
});

onBeforeUnmount(() => {
  if (qrScanner) {
    qrScanner.stop(); // Stop the scanner when the component is unmounted
  }
});
</script>

<style scoped>
.qr-result {
  margin-top: 20px;
  font-size: 1.2em;
  color: #333;
}
</style>
