// frontend/components/adsy-business-network/footer.vue
<template>
  <div
    class="md:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 z-50 shadow-lg"
  >
    <div v-if="user?.user?.id" class="flex justify-between items-center px-2">
      <NuxtLink
        to="/business-network"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/business-network'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
        @click="handleRecentClick"
      >
        <div class="relative">
          <Clock
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/business-network'
                ? 'text-blue-600'
                : 'text-gray-500'
            "
          />
        </div>
        <span>Recent</span>
      </NuxtLink>
      <NuxtLink
        to="/business-network/notifications"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/business-network/notifications'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <Bell
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/business-network/notifications'
                ? 'text-blue-600'
                : 'text-gray-500'
            "
          />
          <span
            class="absolute -top-1 -right-1 bg-blue-600 text-white text-[10px] rounded-full min-w-[16px] h-4 flex items-center justify-center px-1"
          >
            5
          </span>
        </div>
        <span>Notifications</span>
      </NuxtLink>
      <NuxtLink
        :to="`/business-network/profile/${user?.user?.id}`"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === `/business-network/profile/${user?.user?.id}`
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
        @click="handleProfileClick"
      >
        <div class="relative">
          <User
            class="h-6 w-6 mb-1"
            :class="
              $route.path === `/business-network/profile/${user?.user?.id}`
                ? 'text-blue-600'
                : 'text-gray-500'
            "
          />
        </div>
        <span>Profile</span>
      </NuxtLink>
      <NuxtLink
        to="/"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <BarChart2
            class="h-6 w-6 mb-1"
            :class="$route.path === '/' ? 'text-blue-600' : 'text-gray-500'"
          />
        </div>
        <span>Adsy Club</span>
      </NuxtLink>
      <NuxtLink
        to="/adsy-news"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/adsy-news'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <Newspaper
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/adsy-news' ? 'text-blue-600' : 'text-gray-500'
            "
          />
        </div>
        <span>Adsy News</span>
      </NuxtLink>
    </div>
    <div v-else class="flex justify-between items-center px-2">
      <NuxtLink
        to="/business-network"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/business-network'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <Clock
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/business-network'
                ? 'text-blue-600'
                : 'text-gray-500'
            "
          />
        </div>
        <span>Recent</span>
      </NuxtLink>
      <NuxtLink
        to="/auth/login"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/auth/login'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <UIcon
            name="i-ic-sharp-person"
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/auth/login' ? 'text-blue-600' : 'text-gray-500'
            "
          />
        </div>
        <span>Login</span>
      </NuxtLink>
      <NuxtLink
        to="/#micro-gigs"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/#micro-gigs'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <UIcon
            name="i-material-symbols-attach-money"
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/#micro-gigs' ? 'text-blue-600' : 'text-gray-500'
            "
          />
        </div>
        <span>Earn</span>
      </NuxtLink>
      <NuxtLink
        to="/"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <BarChart2
            class="h-6 w-6 mb-1"
            :class="$route.path === '/' ? 'text-blue-600' : 'text-gray-500'"
          />
        </div>
        <span>Adsy Club</span>
      </NuxtLink>
      <NuxtLink
        to="/adsy-news"
        class="flex flex-col items-center py-3 px-3 text-xs relative"
        :class="
          $route.path === '/adsy-news'
            ? 'text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600'
            : 'text-gray-500'
        "
      >
        <div class="relative">
          <Newspaper
            class="h-6 w-6 mb-1"
            :class="
              $route.path === '/adsy-news' ? 'text-blue-600' : 'text-gray-500'
            "
          />
        </div>
        <span>Adsy News</span>
      </NuxtLink>
    </div>
  </div>
</template>

<script setup>
import {
  BarChart2,
  Bell,
  Bookmark,
  Clock,
  Home,
  Newspaper,
  User,
} from "lucide-vue-next";

const { user } = useAuth();
const eventBus = useEventBus();

// Handle Recent menu click
function handleRecentClick() {
  // Emit loading event for Recent menu
  eventBus.emit('start-loading-posts');
}

// Handle Profile menu click
function handleProfileClick() {
  // Emit loading event for Profile menu
  eventBus.emit('start-loading-profile');
}
</script>

// frontend1/src/components/adsy-business-network/footer.tsx
import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  BarChart2,
  Bell,
  Clock,
  Newspaper,
  User,
} from "lucide-react";

// Simulated useAuth hook (replace with your actual implementation)
const useAuth = () => {
  return {
    user: {
      user: {
        id: "123", // Replace with dynamic user ID
      },
    },
  };
};

const Footer: React.FC = () => {
  const { user } = useAuth();
  const router = useRouter();

  const isActive = (path: string) => router.pathname === path;

  return (
    <div className="md:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 z-50 shadow-lg">
      {user?.user?.id ? (
        <div className="flex justify-between items-center px-2">
          <Link href="/business-network">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/business-network")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <Clock
                  className={`h-6 w-6 mb-1 ${
                    isActive("/business-network")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Recent</span>
            </a>
          </Link>
          <Link href="/business-network/notifications">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/business-network/notifications")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <Bell
                  className={`h-6 w-6 mb-1 ${
                    isActive("/business-network/notifications")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
                <span className="absolute -top-1 -right-1 bg-blue-600 text-white text-[10px] rounded-full min-w-[16px] h-4 flex items-center justify-center px-1">
                  5
                </span>
              </div>
              <span>Notifications</span>
            </a>
          </Link>
          <Link href={`/business-network/profile/${user?.user?.id}`}>
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive(`/business-network/profile/${user?.user?.id}`)
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <User
                  className={`h-6 w-6 mb-1 ${
                    isActive(`/business-network/profile/${user?.user?.id}`)
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Profile</span>
            </a>
          </Link>
          <Link href="/">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <BarChart2
                  className={`h-6 w-6 mb-1 ${
                    isActive("/") ? "text-blue-600" : "text-gray-500"
                  }`}
                />
              </div>
              <span>Adsy Club</span>
            </a>
          </Link>
          <Link href="/adsy-news">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/adsy-news")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <Newspaper
                  className={`h-6 w-6 mb-1 ${
                    isActive("/adsy-news")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Adsy News</span>
            </a>
          </Link>
        </div>
      ) : (
        <div className="flex justify-between items-center px-2">
          <Link href="/business-network">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/business-network")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <Clock
                  className={`h-6 w-6 mb-1 ${
                    isActive("/business-network")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Recent</span>
            </a>
          </Link>
          <Link href="/auth/login">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/auth/login")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <i
                  className={`i-ic-sharp-person h-6 w-6 mb-1 ${
                    isActive("/auth/login")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Login</span>
            </a>
          </Link>
          <Link href="/#micro-gigs">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/#micro-gigs")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <i
                  className={`i-material-symbols-attach-money h-6 w-6 mb-1 ${
                    isActive("/#micro-gigs")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Earn</span>
            </a>
          </Link>
          <Link href="/">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <BarChart2
                  className={`h-6 w-6 mb-1 ${
                    isActive("/") ? "text-blue-600" : "text-gray-500"
                  }`}
                />
              </div>
              <span>Adsy Club</span>
            </a>
          </Link>
          <Link href="/adsy-news">
            <a
              className={`flex flex-col items-center py-3 px-3 text-xs relative ${
                isActive("/adsy-news")
                  ? "text-blue-600 after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-blue-600"
                  : "text-gray-500"
              }`}
            >
              <div className="relative">
                <Newspaper
                  className={`h-6 w-6 mb-1 ${
                    isActive("/adsy-news")
                      ? "text-blue-600"
                      : "text-gray-500"
                  }`}
                />
              </div>
              <span>Adsy News</span>
            </a>
          </Link>
        </div>
      )}
    </div>
  );
};

export default Footer;
